# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sv19KrHY9iJctEzat0cISmCdlTECfTkz
"""

from google.colab import files

files.upload()

import os
import zipfile

os.makedirs('/root/.kaggle', exist_ok=True)
!mv kaggle.json /root/.kaggle/

!chmod 600 /root/.kaggle/kaggle.json

import pandas as pd

df = pd.read_csv("marketing_campaign.csv")
df.head()

missing_values = df.isnull().sum()
print("Missing Values:\n", missing_values)

df = pd.read_csv("marketing_campaign.csv", sep="\t")

missing_values = df.isnull().sum()
print("Missing Values:\n", missing_values[missing_values > 0])

df.isnull().sum()

df['Income'] = df['Income'].fillna(df['Income'].median())

df.isnull().sum()

df = df.drop_duplicates()

df['Education'] = df['Education'].str.strip().str.lower()
df['Marital_Status'] = df['Marital_Status'].str.strip().str.lower()

df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'], dayfirst=True, errors='coerce')

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

print(df.dtypes)

df['education'] = df['education'].str.strip().str.lower()
df['marital_status'] = df['marital_status'].str.strip().str.lower()

print(df.dtypes)

df.to_csv('cleaned_dataset.csv', index=False)